# 异常概述与异常体系结构

系统的运行过程中总会遇到一些问题，因为很多问题不是靠代码就能够避免的，比如：客户输入数据的格式，读取的文件是否存在，网络是否始终保持通畅等等。

异常：在Java语言中，将程序执行中发生的不正常情况称为`异常`。（开发过程中的语法错误和逻辑错误不是异常）

异常体系结构：

- `Throwable`（广义上的异常）
  - `Error`：Java虚拟机无法解决的严重问题。如：`JVM`系统内部错误、资源耗尽等严重情况。比如：`StackOverflowError`和`OutOfMemoryError`。一般不编写针对性的代码进行处理。
  - `Exception`（狭义上的异常）：指其它因编程错误或偶然的外在因素导致的一般性问题，可以编写针对性的代码进行处理。例如：空指针访问、试图读取不存在的文件、网络连接中断、数组下标越界等等。
    - 除`RuntimeException`之外的其它所有`Exception`的子类都是编译时异常，又称受检异常(checked exception)。受检异常必须处理，否则编译不通过。
      - `IOException`
        - `FileNotFoundException`
        - `UnknownHostException`
        - `EOFException`
        - `MalformedURLException`
      - `ClassNotFoundException`
      - `CloneNotSupportedException`
    - `RuntimeException`：运行时异常，又称非受检异常(unchecked exception)。
      - `NullPointerException`
      - `IndexOutOfBoundsException`
        - `ArrayIndexOutOfBoundsException`
      - `ClassCastException`
      - `NumberFormatException`
      - `InputMismatchException`
      - `ArithmeticException`

# 常见异常

```java
// 面试题：常见的异常有哪些？举例说明
// 编译时异常，不处理就无法编译
public void test1() {
	File file = new File("hello.txt");
    FileInputStream fis = new FileInputStream(file); // 编译报错：Unhandled exception : java.io.FileNotFoundException
    int data = fis.read(); // 编译报错：Unhandled exception : java.io.IOException
    while (data != -1) {
    	System.out.print((char)data);
        data = fis.read(); // 编译报错：Unhandled exception : java.io.IOException
    }
    fis.close(); // 编译报错：Unhandled exception : java.io.IOException
}
// 运行时异常，运行之后才会抛出
// NullPointerException
public void test2() {
    int[] arr = null;
    System.out.println(arr[3]); // 编译正常，运行报错：java.lang.NullPointerException
    String str = null;
    System.out.println(str.charAt(0)); // 编译正常，运行报错：java.lang.NullPointerException
}
// IndexOutOfBoundsException
public void test3() {
    int[] arr = new int[10];
    System.out.println(arr[10]); // 编译正常，运行报错：java.lang.ArrayIndexOutOfBoundsException: 10
    String str = "abc";
    System.out.println(str.charAt(3)); // 编译正常，运行报错：java.lang.StringIndexOutOfBoundsException: String index out of range: 3
}
// ClassCastException
public void test4() {
    Object obj = new Date();
    String str = (String)obj; // 编译正常，运行报错：java.lang.ClassCastException: java.util.Date cannot be cast to java.lang.String
}
// NumberFormatException
public void test5() {
	String str = "abc";
    int num = Integer.parseInt(str); // 编译正常，运行报错：java.lang.NumberFormatException: For input string: "abc"
}
// InputMismatchException
public void test6() {
    Scanner scanner = new Scanner(System.in);
    int score = scanner.nextInt(); // 输入abc，抛出异常：java.util.InputMismatchException
    System.out.println(score);
    scanner.close();
}
// ArithmeticException
public void test7() {
	int a = 10;
    int b = 0;
    System.out.println(a / b); // 编译正常，运行报错：java.lang.ArithmeticException: / by zero
}
```

# 异常处理机制

## try-catch-finally

```java
try{
    // 可能出现异常的代码
}catch(异常类型1 变量名1) {
    // 处理异常1的方式
}catch(异常类型2 变量名2) {
	// 处理异常2的方式
}catch(异常类型3 变量名3) {
	// 处理异常3的方式
}
....
finally { // finally部分可有可无，前提是有catch
	// 一定会执行的代码
}
```

- `try`
  - 尝试执行的代码，如果出现异常，就会生成一个对应异常类的对象，跳转到对应类型的`catch`代码块，异常后面的代码不会被执行。
  - 一个`try-catch-finally`结构中只能有一个`try`。
  - 在`try`中声明的变量出了`try`的大括号之后就不可以再调用了。解决方法：在`try`之前声明，在`try`里面进行初始化。
- `catch`
  - 捕获异常并进行处理，如果`try`中没有出现异常则不执行。`catch`中的常用方法：① `e.getMessage();`返回一个包含异常信息的`String`。②`e.printStackTrace();`打印堆栈信息。
  - 可以有多个`catch`，但是如果多个`catch`结构中的异常类型有子父类关系，那么子类异常的`catch`结构必须声明在父类的前面。否则编译报错。
  - 前面的`catch`捕获到了异常，后面的`catch`就不会再执行。
- `finally`
  - 一定会被执行的代码，即使`try`中出现异常或`return`。
  - 不能有`return`，因为会覆盖掉`try`和`catch`中的`return`。
  - 不能在`finally`中`throw`异常，会覆盖掉`try`和`catch`中`throw`的异常。`finally`中有异常只能捕获不能抛出。
  - 一个`try-catch-finally`只能有一个`finally`。
  - 像数据库连接、输入输出流、网络编程Socket等资源，`JVM`是不能自动回收的，需要手动进行资源的释放。释放操作一般在`finally`中执行。

> 除了完整的`try-catch-finally`结构，还有特殊的`try-catch`、`try-finally`结构。

> 开发中一般只针对编译时异常进行`try-catch-finally`处理。

## throws

在方法的声明后加上`throws 异常类型1,异常类型2...`

1. `throws + 异常类型`写在方法的声明处。指明此方法执行时可能会抛出的异常类型。当方法体执行时，一旦出现异常，仍会在异常代码处生成一个异常类的对象，此对象符合`throws`后的异常类型时就会被抛出。异常代码之后的代码将不再执行。
2. `thows`只是把异常抛给了方法的调用者，并没有将异常真正地处理掉。最终还是需要`try-catch-finally`来捕获异常。
3. 两种异常处理的使用情景
   1. 如果父类中被重写的方法没有用`throws`方式处理异常，那么子类重写的方法也不能使用`throws`，只能`try-catch`掉。（不破坏多态性）
   2. 执行的主方法中，先后又调用了另外几个方法，这几个方法是递进执行的。这几个方法的异常建议用`throws`处理，在主方法中统一进行`try-catch`。

```java
public void method1() throws FileNotFoundException,IOException {
    File file = new File("hello.txt");
    FileInputStream fis = new FileInputStream(file);
    int data = fis.read();
    while (data != -1) {
        System.out.print((char)data);
        data = fis.read();
    }
    fis.close();
}
```



```java
// 子类重写的方法抛出的异常类型不大于父类被重写的方法抛出的异常类型
public class OverriderTest {
	public static void main(String[] args) {
    	OverriderTest test = new OverriderTest();
        test.display(new SubClass()); // 多态
    }
    public void display(SuperClass s) {
    	try {
        	s.method();
        } catch (IOException e) { // 如果子类抛出的异常类型大于父类抛出的异常类型，此处就捕获不到
        	e.printStackTrace();
        }
    }
}
class SuperClass {
	public void method() throws IOException {}
}
class SubClass extends SuperClass {
    @Override
	public void method() throws FileNotFoundException {} // 只能抛IOException或IOException的子类，如果父类没抛，子类也不能抛。
}
```

# 手动抛出异常throw

异常的处理：抓抛模型

过程一："抛"，程序在正常执行的过程中，一旦出现异常，就会在异常代码处生成一个异常类的对象，并将此对象抛出。一旦抛出对象后，其后代码就不再执行。

​				异常对象的产生：① 系统自动生成的异常对象（`try-catch`和`throws`都是自动生成的） ② 手动生成一个异常对象，并抛出（`throw`）。

过程二："抓"，可以理解为异常的处理方式：① `try-catch-finally` ② `throws`

```java
// 应用场景
public class StudentTest {
	public static void main(String[] args) {
    	Student s = new Student();
        s.regist(-1); // 这一行抛出了异常
        s.show(); // 这一行不会执行
    }
}
class Student {
	private int id;
    public void regist() {
    	if (id > 0) {
            this.id = id;
        } else {
        	// System.out.println("输入的数据非法！"); // 之前的写法，仅仅起到提示作用，后面代码仍会执行
            throw new RuntimeException("输入的数据非法！"); // 提示信息并中断程序，一般都throw运行时异常，throw非运行时异常时要处理
        }
    }
    public void show() {
    	System.out.println("当前学生的id：" + this.id);
    }
}
```

# 自定义异常类

如何自定义异常类？

1. 继承现有的异常结构：`RuntimeException`或`Exception`。
2. 提供序列版本号：`static final long serialVersionUID = -123456L;`。
3. 提供重载的构造器。

```java
public class StudentTest {
	public static void main(String[] args) {
    	try {
        	Student s = new Student();
        	s.regist(-1);
        	s.show();
        } catch(Exception e) {
            System.out.println(e.getMessage());
        }
        
    }
}
class Student {
	private int id;
    public void regist() throws MyException {
    	if (id > 0) {
            this.id = id;
        } else {
            throw new MyException("不能输入负数！");
        }
    }
    public void show() {
    	System.out.println("当前学生的id：" + this.id);
    }
}
class MyException extends RuntimeException {
    static final long serialVersionUID = -123456L;
    public MyException() {}
    public MyException(String msg) {
    	super(msg);
    }
}
```



```java
// 练习一：输出语句的顺序
public class Demo01 {
	static void methodA() {
    	try {
        	System.out.println("进入方法A");
            throw new RuntimeException("制造异常");
        } finally {
        	System.out.println("方法A的finally");
        }
    }
    static void methodB() {
    	try {
        	System.out.println("进入方法B");
            return;
        } finally {
        	System.out.println("方法B的finally");
        }
    }
    public static void main(String[] args) {
    	try {
        	methodA();
        } catch(Exception e) {
        	System.out.println(e.getMessage());
        }
        methodB();
    }
}
// 进入方法A
// 方法A的finally
// 制造异常
// 进入方法B
// 方法B的finally
```

# 总结

异常处理五个关键字：

- 异常处理（抓）
  - 捕获异常
    - `try`：执行可能产生异常的代码
    - `catch`：捕获异常
    - `finally`：无论是否产生异常，其中的代码都会执行
  - 声明抛出异常
    - `throws`：异常的处理，声明方法可能要抛出的异常
- 手动抛出异常（抛）
  - `throw`：异常的生成，手动抛出异常对象

> 上游排污，下游治污

```java
// 面试题
// 结构类似的概念的区别
final 、 finally 、 finalize三者的区别？
throw 和 throws 
Collection 和 Collections
String 、 StringBuffer 、 StringBuilder
ArrayList 和 LinkedList
HashMap 和 LinkedHashMap
重写 和 重载
// 结构不相似的
抽象类 和 接口
== 和 equals()
sleep() 和 wait()
```

